# coding=utf-8
"""Custom exceptions used or raised by tmdb_api."""

__author__ = "p0psicles"
__version__ = "1.0"

__all__ = ["TMDBError", "TMDBUserAbort", "TMDBShowNotFound", "TMDBShowIncomplete",
           "TMDBSeasonNotFound", "TMDBEpisdeNotFound", "TMDBAttributeNotFound"]


class TMDBException(Exception):
    """Any exception generated by tmdb_api."""


class TMDBError(TMDBException):
    """An error with thetmdb.com (Cannot connect, for example)."""


class TMDBUserAbort(TMDBException):
    """User aborted the interactive selection (via the q command, ^c etc)."""


class TMDBShowNotFound(TMDBException):
    """Show cannot be found on thetmdb.com (non-existant show)."""


class TMDBShowIncomplete(TMDBException):
    """Show found but incomplete on thetmdb.com (incomplete show)."""


class TMDBSeasonNotFound(TMDBException):
    """Season cannot be found on thetmdb.com."""


class TMDBEpisdeNotFound(TMDBException):
    """Episode cannot be found on thetmdb.com."""


class TMDBAttributeNotFound(TMDBException):
    """Raised if an episode does not have the requested attribute (such as a episode name)."""
