# coding=utf-8
"""Custom exceptions used or raised by tVMaze_api."""

__author__ = "p0psicles"
__version__ = "1.0"

__all__ = ["TVMazeError", "TVMazeUserAbort", "TVMazeShowNotFound", "TVMazeShowIncomplete",
           "TVMazeSeasonNotFound", "TVMazeEpisodeNotFound", "TVMazeAttributeNotFound"]


class TVMazeException(Exception):
    """Any exception generated by tVMaze_api."""


class TVMazeError(TVMazeException):
    """An error with thetVMaze.com (Cannot connect, for example)."""


class TVMazeUserAbort(TVMazeException):
    """User aborted the interactive selection (via the q command, ^c etc)."""


class TVMazeShowNotFound(TVMazeException):
    """Show cannot be found on thetVMaze.com (non-existant show)."""


class TVMazeShowIncomplete(TVMazeException):
    """Show found but incomplete on thetVMaze.com (incomplete show)."""


class TVMazeSeasonNotFound(TVMazeException):
    """Season cannot be found on thetVMaze.com."""


class TVMazeEpisodeNotFound(TVMazeException):
    """Episode cannot be found on thetVMaze.com"""


class TVMazeAttributeNotFound(TVMazeException):
    """Raised if an episode does not have the requested attribute (such as a episode name)."""
